name: Lootin
version: ${project.version}
main: com.github.sachin.lootin.Lootin
api-version: 1.16
authors: [ sachingorkar ]
softdepend: [Terra,CustomStructures,Oh_the_dungeons_youll_go,PlaceholderAPI,ProtocolLib]
description: Loot per player
api: []


permissions:
  lootin.breakchest.bypass:
    default: op
  lootin.command.reload:
    default: op  